[workspace]
resolver = "2"

members = [
    "helloworld",
    "show-window-with-movie",
    "winit-softbuffer-ab-glyph",
    "winit-softbuffer-fontdue",
    "winit-softbuffer-raw-video",
    "winit-softbuffer",
    "zeroconf-client",
    "zeroconf-server"
]
